### Variáveis de Ambiente
@baseUrl = http://127.0.0.1:8000

### 1. Testar conexão com a API
GET {{baseUrl}}/
Accept: application/json

### 2. Criar uma nova Série (POST)
# O FastAPI validará automaticamente com o Schema (Pydantic)
POST {{baseUrl}}/series/
Content-Type: application/json

{
    "titulo": "The Bear",
    "descricao": "Um jovem chef de alta gastronomia retorna para Chicago para administrar a lanchonete da família.",
    "ano_lancamento": 2022
}

### 3. Listar todas as Séries (GET)
GET {{baseUrl}}/series/
Accept: application/json

### 4. Atualizar uma Série existente (PUT)
PUT {{baseUrl}}/series/1
Content-Type: application/json

{
    "titulo": "The Bear - Temporada 2",
    "descricao": "O restaurante ganha uma nova cara e os chefs evoluem.",
    "ano_lancamento": 2023
}

### Deletar uma Série pelo ID
DELETE {{baseUrl}}/series/1